---
title: "Homework 2"
author: "Edmund Hui"
date: "2023-01-20"
output: github_document
---

```{r}
#install.packages("qrnn")
```
```{r}
library(qrnn)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## load prostate data
prostate <- 
  read.table(url(
    'https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data'))

## subset to training examples
prostate_train <- subset(prostate, train==TRUE)

## plot lcavol vs lpsa
plot_psa_data <- function(dat=prostate_train) {
  plot(dat$lpsa, dat$lcavol,
       xlab="log Prostate Screening Antigen (psa)",
       ylab="log Cancer Volume (lcavol)",
       pch = 20)
}
plot_psa_data()
```


```{r}
############################
## regular linear regression
############################

## L2 loss function
L2_loss <- function(y, yhat)
  (y-yhat)^2

## fit simple linear model using numerical optimization
fit_lin <- function(y, x, loss=L2_loss, beta_init = c(-0.51, 0.75)) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*x))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}

## make predictions from linear model
predict_lin <- function(x, beta)
  beta[1] + beta[2]*x

## fit linear model
lin_beta <- fit_lin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L2_loss)

## compute predictions for a grid of inputs
x_grid <- seq(min(prostate_train$lpsa),
              max(prostate_train$lpsa),
              length.out=100)
lin_pred <- predict_lin(x=x_grid, beta=lin_beta$par)

## plot data
plot_psa_data()

## plot predictions
lines(x=x_grid, y=lin_pred, col='darkgreen', lwd=2)

## do the same thing with 'lm'
lin_fit_lm <- lm(lcavol ~ lpsa, data=prostate_train)

## make predictins using 'lm' object
lin_pred_lm <- predict(lin_fit_lm, data.frame(lpsa=x_grid))

## plot predictions from 'lm'
lines(x=x_grid, y=lin_pred_lm, col='pink', lty=2, lwd=2)
```


```{r}
##################################
## try modifying the loss function
##################################

## custom loss function
custom_loss <- function(y, yhat)
  qrnn::tilted.abs(y-yhat, tau = 0.25)

## tilted loss function tau=0.75
tilt_loss <- function(y, yhat)
  qrnn::tilted.abs(y-yhat, tau = 0.75)

## L1 loss function
L1_loss <- function(y, yhat){
  abs(y-yhat)
}

## plot custom loss function
err_grd <- seq(-1,1,length.out=200)
plot(err_grd, custom_loss(err_grd,0), type='l',
     xlab='y-yhat', ylab='custom loss')

## fit linear model with custom loss
lin_beta_custom <- fit_lin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=custom_loss)

lin_pred_custom <- predict_lin(x=x_grid, beta=lin_beta_custom$par)

# fit linear model with L1 loss 

lin_beta_L1 <- fit_lin(y=prostate_train$lcavol,
                x=prostate_train$lpsa,
                loss=L1_loss)

lin_pred_L1 <- predict_lin(x=x_grid, beta=lin_beta_L1$par)

# fit linear model with tilted tau=0.75

lin_beta_tilt <- fit_lin(y=prostate_train$lcavol,
                x=prostate_train$lpsa,
                loss=tilt_loss)

lin_pred_tilt <- predict_lin(x=x_grid, beta=lin_beta_tilt$par)

## plot data
plot_psa_data()

## plot predictions from L2 loss
lines(x=x_grid, y=lin_pred, col='darkgreen', lwd=2)

## plot predictions from custom loss
lines(x=x_grid, y=lin_pred_custom, col='pink', lwd=2, lty=2)

# plot predictions from tilted tau=0.75
lines(x=x_grid, y=lin_pred_tilt, col='purple', lwd=2, lty=2)

## plot predictions from L1 loss
lines(x=x_grid, y=lin_pred_L1, col='blue', lwd=2, lty=6)

legend(-0.5, 3.9, legend=c("L1 Loss", "L2 Loss", "Tilted Abs Loss (tau=0.25)", "Tilted Abs Loss (tau=0.75)"),
                         col=c("blue", "darkgreen", "pink", "purple"), lty=c(6,1,2,2), cex=0.8)
```
```{r}
##################################
## Modifying Functions for Non Linear Model
##################################

## fit simple linear model using numerical optimization
fit_nl <- function(y, x, loss=L2_loss, beta_init = c(-1.0, 0.0, -0.3 )) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*exp(-beta[3]*x)))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}

## make predictions from squared model
predict_nl <- function(x, beta)
  beta[1] + beta[2]*exp(-beta[3]*x)

nl_beta <- fit_nl(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L2_loss)

nl_pred <- predict_nl(x=x_grid, beta=nl_beta$par)
```

```{r}
##################################
## Other Loss Functions
##################################


# tilted tau=0.25
lin_beta_custom <- fit_nl(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=custom_loss)

lin_pred_custom <- predict_nl(x=x_grid, beta=lin_beta_custom$par)

# fit linear model with L1 loss 

lin_beta_L1 <- fit_nl(y=prostate_train$lcavol,
                x=prostate_train$lpsa,
                loss=L1_loss)

lin_pred_L1 <- predict_nl(x=x_grid, beta=lin_beta_L1$par)

# fit linear model with tilted tau=0.75

lin_beta_tilt <- fit_nl(y=prostate_train$lcavol,
                x=prostate_train$lpsa,
                loss=tilt_loss)

lin_pred_tilt <- predict_nl(x=x_grid, beta=lin_beta_tilt$par)

##################################
## Plotting
##################################

plot_psa_data()

## plot predictions from L2 loss
lines(x=x_grid, y=nl_pred, col='darkgreen', lwd=2)

## plot predictions from custom loss
lines(x=x_grid, y=lin_pred_custom, col='pink', lwd=2, lty=2)

# plot predictions from tilted tau=0.75
lines(x=x_grid, y=lin_pred_tilt, col='purple', lwd=2, lty=2)

## plot predictions from L1 loss
lines(x=x_grid, y=lin_pred_L1, col='blue', lwd=2, lty=6)

legend(-0.5, 3.9, legend=c("L1 Loss", "L2 Loss", "Tilted Abs Loss (tau=0.25)", "Tilted Abs Loss (tau=0.75)"),
                         col=c("blue", "darkgreen", "pink", "purple"), lty=c(6,1,2,2), cex=0.8)

```


